"""
Code Generation Templates — all Python source templates used for generating
standalone LangGraph projects from a workflow definition.

Each constant is a f-string template using .format() placeholders.
"""

# ─── utils.py Template ─────────────────────────────────────────────────────────
UTILS_PY = '''\
"""
utils.py — Shared utilities for this LangGraph workflow.
"""
from __future__ import annotations
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def log_step(node_name: str, message: str) -> None:
    """Log a workflow step with its node name."""
    logger.info(f"[{{node_name}}] {{message}}")


def safe_get(data: dict, key: str, default=None):
    """Safely retrieve a key from a dict, returning a default if missing."""
    return data.get(key, default) if isinstance(data, dict) else default
'''

# ─── helpers.py Template ───────────────────────────────────────────────────────
HELPERS_PY = '''\
"""
helpers.py — HTTP helper for executing API actions inside workflow nodes.

Each action node calls `execute_api_action` with its configuration dictionary.
The result is stored back in the shared workflow state under `output_key`.
"""
from __future__ import annotations
import httpx
from utils import logger


def execute_api_action(state: dict, action_key: str, config: dict) -> dict:
    """
    Execute any HTTP action from a node configuration.

    config keys:
        url           (required) — the endpoint to call
        method        (default GET) — HTTP method
        output_key    (default "last_result") — where to write the response in state
        path_params   (list[{{key, value}}]) — injected into URL path
        query_params  (list[{{key, value}}]) — appended as query string
        header_params (list[{{key, value}}]) — sent as HTTP headers
        body_params   (list/dict) — sent as JSON body (POST/PUT/PATCH only)
    """
    url: str | None = config.get("url")
    method: str = config.get("method", "GET").upper()
    output_key: str = config.get("output_key", "last_result")

    if not url:
        logger.warning(f"[{{action_key}}] No URL configured — skipping.")
        state[output_key] = {{"error": "No URL configured"}}
        return state

    # Resolve path parameters (:key → value)
    for p in config.get("path_params") or []:
        if p and "key" in p and "value" in p:
            url = url.replace(f":{{p[\'key\']}}", str(p["value"]))

    # Build query params
    params = {{
        q["key"]: q["value"]
        for q in (config.get("query_params") or [])
        if q and "key" in q and "value" in q
    }}

    # Build headers
    headers = {{
        h["key"]: h["value"]
        for h in (config.get("header_params") or [])
        if h and "key" in h and "value" in h
    }}

    # Build JSON body
    body_raw = config.get("body_params")
    json_body = None
    if isinstance(body_raw, list):
        json_body = {{b["key"]: b["value"] for b in body_raw if b and "key" in b and "value" in b}}
    elif isinstance(body_raw, dict):
        json_body = body_raw

    logger.info(f"[{{action_key}}] {{method}} {{url}}")

    try:
        with httpx.Client() as client:
            response = client.request(
                method=method,
                url=url,
                params=params,
                headers=headers,
                json=json_body if method in ("POST", "PUT", "PATCH") else None,
                timeout=15.0,
            )
            response.raise_for_status()
            result = response.json()
            logger.info(f"[{{action_key}}] ✓ {{response.status_code}}")
            state[output_key] = result
            state["last_result"] = result
            state["http_response"] = {{"status_code": response.status_code, "url": str(response.url)}}
    except httpx.HTTPStatusError as e:
        logger.error(f"[{{action_key}}] HTTP {{e.response.status_code}}: {{e.response.text}}")
        state[output_key] = {{"error": f"HTTP {{e.response.status_code}}", "detail": e.response.text}}
    except Exception as e:
        logger.error(f"[{{action_key}}] Request failed: {{e}}")
        state[output_key] = {{"error": "Request failed", "detail": str(e)}}

    return state
'''

# ─── langgraph_workflow.py Template ────────────────────────────────────────────
LANGGRAPH_WORKFLOW_PY_HEADER = '''\
"""
langgraph_workflow.py — Auto-generated LangGraph workflow.

DO NOT edit this file manually — regenerate it from the Tensaw Skill Studio.
"""
from __future__ import annotations
from typing import TypedDict, Any
from langgraph.graph import StateGraph, END
from helpers import execute_api_action


# ─── Shared Workflow State ───────────────────────────────────────────────────
class WorkflowState(TypedDict, total=False):
    """State dict carried across every node in this graph."""
    last_result: Any
    http_response: Any
    saved_data: Any
    final_reply: str
    condition_result: str
    logs: list[str]

'''

LANGGRAPH_NODE_FN_TEMPLATE = '''\
def {fn_name}(state: WorkflowState) -> WorkflowState:
    """Node: {label} — action_key: {action_key}"""
    config = {config_repr}
    return execute_api_action(state, "{action_key}", config)

'''

LANGGRAPH_PASSTHROUGH_FN_TEMPLATE = '''\
def {fn_name}(state: WorkflowState) -> WorkflowState:
    """Node: {label} — pass-through (no action configured)"""
    return state

'''

LANGGRAPH_BUILDER_HEADER = '''\
# ─── Graph Construction ──────────────────────────────────────────────────────
builder = StateGraph(WorkflowState)

'''

LANGGRAPH_ADD_NODE = 'builder.add_node("{lg_name}", {fn_name})\n'
LANGGRAPH_SET_ENTRY = 'builder.set_entry_point("{root}")\n'
LANGGRAPH_ADD_EDGE = 'builder.add_edge("{source}", "{target}")\n'
LANGGRAPH_ADD_CONDITIONAL_COMMENT = '# Conditional: {source} → {target} if condition == {value}\n'
LANGGRAPH_TERMINAL_EDGE = 'builder.add_edge("{leaf}", END)\n'
LANGGRAPH_FOOTER = '\ngraph = builder.compile()\n'

# ─── main.py Template ──────────────────────────────────────────────────────────
MAIN_PY = '''\
"""
main.py — Entry point to execute this LangGraph workflow.

Usage:
    python main.py
"""
from langgraph_workflow import graph, WorkflowState


def run():
    initial_state: WorkflowState = {{
        "logs": [],
        "last_result": None,
        "http_response": None,
        "saved_data": None,
        "final_reply": "",
        "condition_result": "",
    }}
    config = {{"configurable": {{"thread_id": "default_session"}}}}
    final_state = graph.invoke(initial_state, config=config)

    print("\\n✅ Workflow Complete")
    print(f"  Last Result : {{final_state.get(\'last_result\')}}")
    print(f"  HTTP Response: {{final_state.get(\'http_response\')}}")
    return final_state


if __name__ == "__main__":
    run()
'''

# ─── requirements.txt Template ─────────────────────────────────────────────────
REQUIREMENTS_TXT = '''\
langgraph>=0.2.0
langchain-core>=0.1.0
httpx>=0.27.0
pydantic>=2.0.0
typing_extensions>=4.9.0
'''

# ─── README.md Template ────────────────────────────────────────────────────────
README_MD = '''\
# {workflow_name} — LangGraph Workflow

Auto-generated by **Tensaw Skill Studio**.

---

## 📁 File Structure

| File | Purpose |
|------|---------|
| `langgraph_workflow.py` | Core LangGraph graph definition with all nodes and edges |
| `helpers.py` | Generic HTTP action executor (powered by `httpx`) |
| `utils.py` | Shared logging and utility functions |
| `main.py` | Entry point to run the workflow locally |
| `requirements.txt` | Python dependencies |

---

## 🚀 Quick Start

```bash
# 1. Install dependencies
pip install -r requirements.txt

# 2. Run the workflow
python main.py
```

---

## 🔗 Workflow Nodes ({node_count} nodes)

{node_table}

---

## 🌐 API Endpoints Called

{endpoint_table}

---

## 🔄 How to Invoke from Python

```python
from langgraph_workflow import graph, WorkflowState

state: WorkflowState = {{
    "logs": [],
    "last_result": None,
    "http_response": None,
}}
config = {{"configurable": {{"thread_id": "my_session"}}}}
result = graph.invoke(state, config=config)
print(result["last_result"])
```

---

*Generated by Tensaw Skill Studio — Do not edit manually.*
'''
